export { default as Footer } from "./Footer"
export { default as PageTemplate } from "./PageTemplate"
export { default as ScrollToTop } from "./ScrollToTop"
export { default as ColorSwitcher } from "./ColorSwitcher"
export { default as CustomTooltip } from "./CustomTooltip"
export { default as CustomMenu } from "./CustomMenu"
export { default as CustomSnackbar } from "./CustomSnackbar"
export { default as Wrapper } from "./Wrapper"
export * from "./UI"
